import Head from "next/head";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [list, setList] = useState([]);
  const [task, setTask] = useState("");

  // Charge la liste depuis le local storage
  useEffect(() => {
    const storage = JSON.parse(localStorage.getItem("list"));
    if (storage) {
      setList(storage);
    }
  }, []);

  // Ajouter en local storage
  useEffect(() => {
    list.length > 0 && localStorage.setItem("list", JSON.stringify(list));
  }, [list]);

  const delet = (index) => {
    const newTodo = list.filter((_, i) => i !== index);
    setList(newTodo);
  };

  const add = () => {
    if (task.trim() !== "") {
      setList([...list, task]);
      setTask("");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>ToDo list</h1>
        <div className="form">
          <input
            type="text"
            placeholder="Add a new task"
            value={task}
            onChange={(e) => setTask(e.target.value)}
          />
          <button className="add_btn" onClick={add}>
            Add task
          </button>
        </div>
        <div className="content">
          {list.map((list, index) => {
            return (
              <div className="li" key={index}>
                <p>{list}</p>
                <button className="delete_button" onClick={() => delet(index)}>
                  Delete
                </button>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
